/* eslint-disable prettier/prettier */
export const GET_SYNCED_SCREEN_REQUEST = 'GET_SYNCED_SCREEN_REQUEST';
export const GET_SYNCED_SCREEN_SUCCESS = 'GET_SYNCED_SCREEN_SUCCESS';
export const GET_SYNCED_SCREEN_FAIL = 'GET_SYNCED_SCREEN_FAIL';

export const SCREEN_DETAILS_REQUEST = 'SCREEN_DETAILS_REQUEST';
export const SCREEN_DETAILS_SUCCESS = 'SCREEN_DETAILS_SUCCESS';
export const SCREEN_DETAILS_FAIL = 'SCREEN_DETAILS_FAIL';

export const SCREEN_NAME_EDIT_REQUEST = 'SCREEN_NAME_EDIT_REQUEST';
export const SCREEN_NAME_EDIT_SUCCESS = 'SCREEN_NAME_EDIT_SUCCESS';
export const SCREEN_NAME_EDIT_FAIL = 'SCREEN_NAME_EDIT_FAIL';
export const SCREEN_NAME_EDIT_RESET = 'SCREEN_NAME_EDIT_RESET';

export const CHECK_PLAYLIST_REQUEST = 'CHECK_PLAYLIST_REQUEST';
export const CHECK_PLAYLIST_SUCCESS = 'CHECK_PLAYLIST_SUCCESS';
export const CHECK_PLAYLIST_FAIL = 'CHECK_PLAYLIST_FAIL';

export const GET_LOCAL_MEDIA_REQUEST = 'GET_LOCAL_MEDIA_REQUEST';
export const GET_LOCAL_MEDIA_SUCCESS = 'GET_LOCAL_MEDIA_SUCCESS';
export const GET_LOCAL_MEDIA_FAIL = 'GET_LOCAL_MEDIA_FAIL';

export const DOWNLOAD_CAMPAIGNS_REQUEST = 'DOWNLOAD_CAMPAIGNS_REQUEST';
export const DOWNLOAD_CAMPAIGNS_SUCCESS = 'DOWNLOAD_CAMPAIGNS_SUCCESS';
export const DOWNLOAD_CAMPAIGNS_FAIL = 'DOWNLOAD_CAMPAIGNS_FAIL';
